applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name="inicio",
    ),
    path(
        'listar-todos-empleados/',
        views.ListAllEmpleados.as_view(),
        name="lista_empleados",
    ),
    path(
        'listar-todos-empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="lista_empleados_admin",
    ),
    path(
        'lista-por-departamento/<name>/',
        views.ListByAreaEmpleado.as_view(),
        name="filtro_departamento",
    ),
    path(
        'buscar-empleado/',
        views.ListEmpleadoByKword.as_view(),
        name="buscar_empleado",
    ),
    path(
        'buscar-por-trabajo/',
        views.ListByJob.as_view(),
        name="buscar_por_trabajo",
    ),
    path(
        'buscar-por-habilidades/',
        views.ListHabilidadesEmpleado.as_view(),
        name="buscar_por_habilidades",
    ),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name="detalle_empleado",
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name="agregar_empleado"
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name="correcto",
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name="modificar_empleado",
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name="eliminar_empleado",
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos el path de las urls de las apps
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField
# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField("Habilidad", max_length=50)

    class Meta:
        verbose_name = "Habilidad"
        verbose_name_plural = "Habilidades empleados"
    
    def __str__(self):
        return str(self.id) + "-" + self.habilidad


class Empleado(models.Model):
    """ modelo para tabla empleado """
    JOB_CHOICES = (
        ("contador", "Contador"),
        ("administrador", "Administrador"),
        ("economista", "Economista"),
        ("otro", "Otro"),
    )
    last_name = models.CharField("Apellidos", max_length=50)
    first_name = models.CharField("Nombres", max_length=50)
    full_name = models.CharField("Nombre completo", max_length=120, blank=True)
    job = models.CharField("Trabajo", max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField("Avatar", upload_to="empleado", blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField("Coloque descripción", blank=True)

    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"
        ordering = ["last_name"]
        unique_together = ("first_name", "departamento")

    def __str__(self):
        return str(self.id) + "-" + self.last_name + "-" + self.first_name

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)
from .models import Empleado, Habilidades
# Create your views here.


class InicioView(TemplateView):
    """Pagina de inicio"""
    template_name = "inicio.html"


class ListAllEmpleados(ListView):
    """ Lista de todos los empleados """
    template_name = "persona/list_all.html"
    paginate_by = 5
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
    )
        return lista


class ListAllEmpleadosAdmin(ListView):
    """ Lista de todos los empleados """
    template_name = "persona/list_all_admin.html"
    paginate_by = 10
    ordering = 'last_name'
    context_object_name = 'empleados'
    model = Empleado


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = [
        "first_name",
        "last_name",
        "job",
        "departamento",
        "habilidades",
    ]
    success_url = reverse_lazy("persona_app:lista_empleados_admin")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST)
        return super(EmpleadoUpdateView, self).post(request, *args, **kwargs)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy("persona_app:lista_empleados_admin")


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"


class ListByAreaEmpleado(ListView):
    """ Lista empleados por area """
    template_name = "persona/list_by_area.html"
    context_object_name = "area"

    def get_queryset(self):
        area = self.kwargs["name"]
        lista = Empleado.objects.filter(
        departamento__name=area
    )
        return lista


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    fields = [
        "first_name",
        "last_name",
        "job",
        "departamento",
        "habilidades",
        "avatar",
    ]
    success_url = reverse_lazy("persona_app:correcto")

    def form_valid(self, form):
        #Logica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + " " + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


    # 1. Lista todos los empleados de la empresa
    # 2. Listar todos los empleados que pertenecen a un area de la empresa
    # 3. Listar empleados por trabajo
    # 4. Listar los empleados por palabra clave
    # 5. Listar habilidades de un empleado


class ListByJob(ListView):
    """Lista empleados por trabajo"""
    template_name = "persona/by_job.html"
    context_object_name = "empleados"

    def get_queryset(self):
        job_key = self.request.GET.get("jkey",)
        lista = Empleado.objects.filter(
            job=job_key
    )
        return lista


class ListEmpleadoByKword(ListView):
    """ Lista empleados por palabra clave """
    template_name = "persona/by_kword.html"
    context_object_name = "empleados"

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
        first_name=palabra_clave
    )
        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = "persona/por_habilidades.html"
    context_object_name = "habilidades"


    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", int(1))
        empleado = Empleado.objects.get(id=palabra_clave)
        return empleado.habilidades.all()

        # empleado = Empleado.objects.get(id=8)
        # return empleado.habilidades.all()



class SuccessView(TemplateView):
    template_name = "persona/success.html"

templates/persona/add.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Registrar Empleado
{% endblock tittle %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
<!-- Inicio formularios -->
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}            
            <div class="medium-6 cell">
                <label>Nombres:
                  {{ form.first_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                  {{ form.last_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                  {{ form.job }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                  {{ form.departamento }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Habilidades:
                  {{ form.habilidades }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Foto de perfil:
                  {{ form.avatar }}
                </label>
            </div>
            <div class="medium-12 cell">
                <button class="button" type="submit">Agregar</button>
            </div>
        </form>
<!-- finaliza formularios -->
    </div>
</div>
  

{% endblock content %}

templates/persona/by_job.html
<h1>Buscar empleados por trabajo</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="jkey" name="jkey" placeholder="Ingrese trabajo aqui">
    <button type="submit">Buscar</button>
</form>
<h3>Lista resultados</h3>
<ul>
    
    {% for e in empleados %}
        <li>{{ e }}</li>
    {% endfor %}
        
</ul>

templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>
<h3>Lista resultados</h3>
<ul>
    
    {% for e in empleados %}
        <li>{{ e }}</li>
    {% endfor %}
        
</ul>

templates/persona/delete.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Eliminar Empleado
{% endblock tittle %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado</h1>
        <div class="cell">
            <form class="grid-x" method="POST">{% csrf_token %}
                <div class="medium-7 cell callout alert">
                    <p style="font-weight: bolder;">
                        ¿Realmente desea eliminar el empleado 
                        {{ empleado.last_name }} {{ empleado.first_name }}?
                    </p>
                    <button type="submit" class="alert button">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
  

{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    {{ object.full_name }}
{% endblock tittle %}
    
{% block content %}
    
{% include 'includes/header.html' %}

<div class="grid-container">
    
    <div class="grid-x">
        <div class="cell">
            <h3>Detalle de empleado</h3>
        </div>
            <div class="cell-6 callout secondary">
                <h4>
                    {{ empleado.full_name }}
                </h4>
            </div>
        <div class="cell">
            <h3>Datos</h3>
        </div>
        <div class="cell grid-x grid-margin-x callout primary align-center-middle">
            <table class="medium-6 cell hover align-self-middle">
                <tr>
                    <th width="20">Apellidos:</th>
                    <td>{{ empleado.last_name }}</td>
                </tr>
                <tr>
                    <th width="20">Nombres:</th>
                    <td>{{ empleado.first_name }}</td>
                </tr>
                <tr>
                    <th width="20">Trabajo:</th>
                    <td>{{ empleado.job }}</td>
                </tr>
                <tr>
                    <th width="20">Departamento:</th>
                    <td>{{ empleado.departamento.name }}</td>
                </tr>
                <tr>
                    <th width="20" style="vertical-align: 10px;">Habilidades:</th>
                    <td>
                        <ul class="vertical menu">
                            {% for h in empleado.habilidades.all %}

                            <li>{{ h.habilidad }}</li>
                                
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </table>
            {% if empleado.avatar %}
            <div class="medium-4 cell">
                <img src="{{ empleado.avatar.url }}">
            </div>
            {% else %}
            <div class="medium-4 cell">
                <img src="/media/default-avatar.png">
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

templates/persona/list_all.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Lista de Empleados
{% endblock tittle %}
    
{% block content %}
    
{% include 'includes/header.html' %}

<div class="grid-container">
    <!-- Titulo -->
    <div class="grid-x">
        <h1 class="cell">Empleados</h1>

        <!-- Buscador y boton -->
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-5">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        
        <!-- lista de empleados -->
        <div class="cell callout primary">
            <table class="hover">
                <thead>
                <tr>
                    <th width="20">ID</th>
                    <th>Apellidos</th>
                    <th>Nombres</th>                
                    <th>Departamento</th>
                    <th width="20">Acción</th>
                </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                            
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.departamento.name }}</td>
                        <td>
                            <a class="button warning" href="{% url 'persona_app:detalle_empleado' e.id %}">Ver</a>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- Termina lista de empleados -->

        <!-- Paginacion -->
        <div class="cell">
            {% if is_paginated %}

            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}

                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Anterior</a>
                        <span class="show-for-sr">page</span>
                    </li>
                    {% else %}

                    <li class="pagination-previous disabled">Anterior<span class="show-for-sr">page</span></li>
                    
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                    {% ifequal pagina page_obj.number %} 
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{ pagina }}" aria-label="Page {{ pagina }}">{{ pagina }}</a></li>
                    {% endifequal %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">
                            Siguiente<span class="show-for-sr">page</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="pagination-next disabled">Siguiente<span class="show-for-sr">page</span></li>
                    {% endif %}
                </ul>
            </nav> 
            {% endif %}
        </div>
        <!-- Termina paginacion -->

    </div>
</div>
    

{% endblock content %}

templates/persona/list_all_admin.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Administrador de Empleados
{% endblock tittle %}
    
{% block content %}
    
{% include 'includes/header.html' %}

<div class="grid-container">
    <!-- Titulo -->
    <div class="grid-x">
        <h1 class="cell">Administrador de Empleados</h1>

        <!-- lista de empleados -->
        <div class="cell callout primary">
            <table class="hover">
                <thead>
                <tr>
                    <th width="20">ID</th>
                    <th>Apellidos</th>
                    <th>Nombres</th>                
                    <th>Departamento</th>
                    <th>Acción</th>
                </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                            
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.departamento.name }}</td>
                        <td class="grid-margin-x">
                            <div class="cell" style="float: left;">
                                <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                            </div>
                            <div class="cell" style="float: left;">
                                <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                            </div>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- Termina lista de empleados -->

        <!-- Paginacion -->
        <div class="cell">
            {% if is_paginated %}

            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}

                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Anterior</a>
                        <span class="show-for-sr">page</span>
                    </li>
                    {% else %}

                    <li class="pagination-previous disabled">Anterior<span class="show-for-sr">page</span></li>
                    
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                    {% ifequal pagina page_obj.number %} 
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{ pagina }}" aria-label="Page {{ pagina }}">{{ pagina }}</a></li>
                    {% endifequal %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">
                            Siguiente<span class="show-for-sr">page</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="pagination-next disabled">Siguiente<span class="show-for-sr">page</span></li>
                    {% endif %}
                </ul>
            </nav> 
            {% endif %}
        </div>
        <!-- Termina paginacion -->

    </div>
</div>
    

{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Lista de Empleados por Departamento
{% endblock tittle %}
    
{% block content %}
    
{% include 'includes/header.html' %}
    
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de empleados por Departamento</h1>

        <!-- lista de empleados -->
        <div class="cell callout primary">
            <table class="hover">
                <thead>
                <tr>
                    <th width="20">ID</th>
                    <th>Apellidos</th>
                    <th>Nombres</th>                
                    <th>Departamento</th>
                    <th width="20">Acción</th>
                </tr>
                </thead>
                <tbody>
                    {% for a in area %}
                            
                    <tr>
                        <td>{{ a.id }}</td>
                        <td>{{ a.last_name }}</td>
                        <td>{{ a.first_name }}</td>
                        <td>{{ a.departamento.name }}</td>
                        <td>
                            <a class="button warning" href="{% url 'persona_app:detalle_empleado' a.id %}">Ver</a>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- Termina lista de empleados -->
        
    </div>
</div>




{% endblock content %}

templates/persona/por_habilidades.html
<h1>Habilidades de empleados</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>
<ul>
    
    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
        
</ul>

templates/persona/success.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Guardado
{% endblock tittle %}


{% block content %}


<div class="grid-container">
    <div class="grid-x grid-margin-x align-center-middle">
        <div class="medium-6 cell callout success" style="margin-top: 20px;">
            <h3 class="text-center">Felicidades</h3>
            <p class="text-center">Se guardó correctamente el empleado.</p>
            <p class="text-center">En 5 segundos serás redireccionado.</p>
        </div>
        <meta http-equiv="refresh" content="5;url={% url 'persona_app:agregar_empleado' %}">
    </div>
</div>

  

{% endblock content %}

templates/persona/update.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Editar Empleado
{% endblock tittle %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar datos de empleado</h1>

        <div class="cell callout primary">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombres: 
                      {{ form.first_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellidos: 
                      {{ form.last_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Trabajo: 
                      {{ form.job }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Departamento: 
                      {{ form.departamento }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Habilidades: 
                      {{ form.habilidades }}
                    </label>
                </div>

                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form> 
        </div>
    </div>
</div>
  

{% endblock content %}