applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "departamento_app"

urlpatterns = [
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name="new_departamento",
    ),
    path(
        'lista-departamentos/',
        views.DepartamentoListView.as_view(),
        name="lista_departamentos",
    ),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name="inicio",
    ),
    path(
        'listar-todos-empleados/',
        views.ListAllEmpleados.as_view(),
        name="lista_empleados",
    ),
    path(
        'listar-todos-empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="lista_empleados_admin",
    ),
    path(
        'lista-por-departamento/<name>/',
        views.ListByAreaEmpleado.as_view(),
        name="filtro_departamento",
    ),
    path(
        'buscar-empleado/',
        views.ListEmpleadoByKword.as_view(),
        name="buscar_empleado",
    ),
    path(
        'buscar-por-trabajo/',
        views.ListByJob.as_view(),
        name="buscar_por_trabajo",
    ),
    path(
        'buscar-por-habilidades/',
        views.ListHabilidadesEmpleado.as_view(),
        name="buscar_por_habilidades",
    ),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name="detalle_empleado",
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name="agregar_empleado"
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name="correcto",
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name="modificar_empleado",
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name="eliminar_empleado",
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos el path de las urls de las apps
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li><a href="{% url 'persona_app:inicio' %}">Inicio</a></li>
        <li><a href="{% url 'persona_app:lista_empleados' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:lista_departamentos' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:lista_empleados_admin' %}">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li>
            <a href=" {% url 'persona_app:agregar_empleado' %}" class="button">
              Nuevo empleado
            </a>
        </li>
        <li>
            <a href=" {% url 'departamento_app:new_departamento' %}" class="button" style="margin-left: 15px;">
              Nuevo deparmento
            </a>
        </li>
      </ul>
    </div>
</div>