applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "departamento_app"

urlpatterns = [
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name="new_departamento",
    ),
    path(
        'lista-departamentos/',
        views.DepartamentoListView.as_view(),
        name="lista_departamentos",
    ),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name="inicio",
    ),
    path(
        'listar-todos-empleados/',
        views.ListAllEmpleados.as_view(),
        name="lista_empleados",
    ),
    path(
        'listar-todos-empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="lista_empleados_admin",
    ),
    path(
        'lista-por-departamento/<name>/',
        views.ListByAreaEmpleado.as_view(),
        name="filtro_departamento",
    ),
    path(
        'buscar-empleado/',
        views.ListEmpleadoByKword.as_view(),
        name="buscar_empleado",
    ),
    path(
        'buscar-por-trabajo/',
        views.ListByJob.as_view(),
        name="buscar_por_trabajo",
    ),
    path(
        'buscar-por-habilidades/',
        views.ListHabilidadesEmpleado.as_view(),
        name="buscar_por_habilidades",
    ),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name="detalle_empleado",
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name="agregar_empleado"
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name="correcto",
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name="modificar_empleado",
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name="eliminar_empleado",
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos el path de las urls de las apps
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField("Nombre", max_length=50, blank=True)
    shor_name = models.CharField("Nombre corto", max_length=20, unique=True)
    inactive = models.BooleanField("Inactivo", default=False)

    class Meta:
        verbose_name = "Mi Departamento"
        verbose_name_plural = "Areas de la empresa"
        ordering = ["name"]
        unique_together = ("name", "shor_name")

    def __str__(self):
        return str(self.id) + "-" + self.name + "-" + self.shor_name

applications/departamento/forms.py
from django import forms


class NewDepartamentoForm(forms.Form):
    """NewDepartamentoForm definition."""
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=50, required=False)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from .forms import NewDepartamentoForm
from applications.persona.models import Empleado
from .models import Departamento
from django.views.generic import (
    ListView,
)
# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = "departamento"
    paginate_by = 5

    def get_queryset(self):
        dpto = self.request.GET.get("kword", "")
        lista = Departamento.objects.filter(
            name__icontains=dpto
    )
        return lista



class NewDepartamentoView(FormView):
    template_name = "departamento/new_departamento.html"
    form_class = NewDepartamentoForm
    success_url = "."

    def form_valid(self, form):
        depa = Departamento(
            name=form.cleaned_data["departamento"],
            shor_name=form.cleaned_data["shorname"],
        )
        depa.save()

        nombre = form.cleaned_data["nombre"]
        apellido = form.cleaned_data["apellido"]
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job="administrador",
            departamento=depa,
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Lista de Departamentos
{% endblock tittle %}
    
{% block content %}
    
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Areas</h1>

        <!-- Buscador y boton -->
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-5">
                <input type="text" id="kword" name="kword" placeholder="Buscar Departamento">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <!-- termina buscador y boton -->

        <!-- lista de departamentos -->
        <div class="cell callout primary">
            <table class="hover">
                <tbody>
                    
                    {% for d in departamento %}
                    <tr>
                        <td>{{ d.name }}</td>
                        <td>{{ d.shor_name }}</td>
                        <td>
                            <a class="button warning" href="{% url 'persona_app:filtro_departamento' d.name %}">
                                Ver Empleados
                            </a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        <!-- Termina lista de departamento -->

        <!-- Paginacion -->
        <div class="cell">
            {% if is_paginated %}

            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}

                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous page">Anterior</a>
                        <span class="show-for-sr">page</span>
                    </li>
                    {% else %}

                    <li class="pagination-previous disabled">Anterior<span class="show-for-sr">page</span></li>
                    
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                    {% ifequal pagina page_obj.number %} 
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{ pagina }}" aria-label="Page {{ pagina }}">{{ pagina }}</a></li>
                    {% endifequal %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">
                            Siguiente<span class="show-for-sr">page</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="pagination-next disabled">Siguiente<span class="show-for-sr">page</span></li>
                    {% endif %}
                </ul>
            </nav> 
            {% endif %}
        </div>
        <!-- Termina paginacion -->
    </div>
</div>


{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% load static %}

{% block tittle %}
    Registrar Departamento
{% endblock tittle %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
<!-- Inicio formularios empleado -->
        <form class="cell grid-x grid-margin-x callout" method="POST" style="margin-top: 15px;">{% csrf_token %}   
            <h1 class="cell">Registrar Empleado</h1>         
            <div class="medium-6 cell">
                <label>Nombres:
                  {{ form.nombre }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                  {{ form.apellido }}
                </label>
            </div>
<!-- Inicio formularios departamento -->
            <h1 class="cell">Registrar Departamento</h1>
            <div class="medium-6 cell">
                <label>Departamento:
                {{ form.departamento }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Nombre corto:
                {{ form.shorname }}
                </label>
            </div>
            <div class="medium-12 cell">
                <button class="button" type="submit">Agregar</button>
            </div>
        </form>
<!-- finaliza formularios -->
    </div>
</div>
  

{% endblock content %}

<h1>Nuevo Departamento</h1>

<form action="" method="post">{% csrf_token %}
    <h3>Datos de empleado</h3>
    <p>
        Nombre: {{ form.nombre }}
    </p>
    <p>
        Apellido: {{ form.apellido }}
    </p>
    <h3>Datos de departamento</h3>
    <p>
       Departamento: {{ form.departamento }}
    </p>
    <p>
       Nombre corto: {{ form.shorname }}
    </p>
    <button type="submit">Agregar</button>
</form>